version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metachatdb
      MYSQL_USER: ohgiraffers
      MYSQL_PASSWORD: ohgiraffers
    ports:
      - "10000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ohgiraffers
      MONGO_INITDB_ROOT_PASSWORD: ohgiraffers
      MONGO_INITDB_DATABASE: metachatmongodb
    ports:
      - "10001:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mysql_data:
  mongodb_data: