server:
  port: 8123

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:10000/metachatdb
    username: ohgiraffers
    password: ohgiraffers
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc: TRACE

jwt:
  expiration_time: 86400000 # 1일
  secret: ${JWT_SECRET}
