CREATE TABLE TBL_USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_PASS VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    USER_ROLE VARCHAR(50),
    USER_STATE VARCHAR(50)
);


CREATE TABLE WORLD (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    WORLD_NAME VARCHAR(255) NOT NULL,
    WORLD_PASSWORD VARCHAR(255) NOT NULL
);



